/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import exceptions.InvalidDateException;
import exceptions.InvalidTimeException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Car;
import model.DateTime;
import model.PicoYPlaca;



/**
 *
 * @author juanc
 */
public class JFInputData extends javax.swing.JFrame {

    /**
     * Creates new form JFInputData
     */
    public JFInputData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FTFCarPlate = new javax.swing.JFormattedTextField();
        FTFDate = new javax.swing.JFormattedTextField();
        FTFTime = new javax.swing.JFormattedTextField();
        BTNSubmit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pico Y Placa Predictor");

        jLabel2.setText("Car Plate");

        jLabel3.setText("Date");

        jLabel4.setText("Time");

        FTFCarPlate.setColumns(8);
        try {
            FTFCarPlate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTFCarPlate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTFCarPlateMouseClicked(evt);
            }
        });
        FTFCarPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFCarPlateActionPerformed(evt);
            }
        });

        FTFDate.setColumns(10);
        try {
            FTFDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTFDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTFDateMouseClicked(evt);
            }
        });

        FTFTime.setColumns(5);
        try {
            FTFTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTFTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTFTimeMouseClicked(evt);
            }
        });
        FTFTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFTimeActionPerformed(evt);
            }
        });

        BTNSubmit.setText("Check Pico y Placa");
        BTNSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSubmitActionPerformed(evt);
            }
        });

        jLabel5.setText("Ex: PVC-0390");

        jLabel6.setText("Format: dd/mm/yyyy");

        jLabel7.setText("Format: HH:mm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(BTNSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FTFTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(FTFDate))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                        .addComponent(FTFCarPlate)))))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FTFCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTFDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTFTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(BTNSubmit)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTFCarPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFCarPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFCarPlateActionPerformed

    private void FTFTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFTimeActionPerformed

    private void BTNSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSubmitActionPerformed
        if(checkEmptyFields()){
            JOptionPane.showMessageDialog(null, 
                    "ALL FIELDS MUST BE FILLED",
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
                DateTime dateTime = new DateTime(FTFDate.getText(),FTFTime.getText());
                if(dateTime.checkValidDateFormat() && dateTime.checkValidTimeFormat() ){
                    Car car = new Car(FTFCarPlate.getText());
                    
                    PicoYPlaca picoYPlaca = new PicoYPlaca(car,dateTime);
                
                    if(picoYPlaca.checkPlateRestriction()){
                         
                         JOptionPane.showMessageDialog(null, 
                         "CAUTION! YOUR CAR CANNOT "
                         + "BE ON THE ROAD AT THE MOMENT",
                         "Pico y Placa Information", 
                         JOptionPane.WARNING_MESSAGE); 
                         cleanValues();
                         return;
                    }
                    
                    JOptionPane.showMessageDialog(null, 
                    "YOU CAN BE ON THE ROAD! :D",
                    "Pico y Placa Information", 
                    JOptionPane.INFORMATION_MESSAGE); 
                    
                    cleanValues();
                   
                }
            }catch(InvalidDateException e){
               JOptionPane.showMessageDialog(null, 
                    "INVALID DATE FORMAT",
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }catch(InvalidTimeException e){
               JOptionPane.showMessageDialog(null, 
                    "INVALID TIME FORMAT",
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_BTNSubmitActionPerformed

    
    private boolean checkEmptyFields(){
        
        return 
                !FTFCarPlate.isEditValid() ||
                !FTFDate.isEditValid() ||
                !FTFTime.isEditValid();
    }
    
    private void cleanValues(){
         FTFCarPlate.setValue(null);
           FTFDate.setValue(null);
           FTFTime.setValue(null);
    }
     
    
    private void FTFCarPlateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTFCarPlateMouseClicked
        FTFCarPlate.setCaretPosition(0);       
    }//GEN-LAST:event_FTFCarPlateMouseClicked

    private void FTFDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTFDateMouseClicked
       FTFDate.setCaretPosition(0);
        
    }//GEN-LAST:event_FTFDateMouseClicked

    private void FTFTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTFTimeMouseClicked
        FTFTime.setCaretPosition(0);
    }//GEN-LAST:event_FTFTimeMouseClicked

    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInputData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSubmit;
    private javax.swing.JFormattedTextField FTFCarPlate;
    private javax.swing.JFormattedTextField FTFDate;
    private javax.swing.JFormattedTextField FTFTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
